from . import prestashop_store_details
from . import prestashop_operation_details
from . import product_category
from . import res_partner
from . import product
from . import sale_order
from . import product_attribute
from . import prestashop_product_detail
from . import stock_inventory